name: Hyperverse
version: ${project.version}
main: com.github.sauilitired.hyperverse.Hyperverse
api-version: 1.13
load: STARTUP
authors: [Citymonstret]
description: A minecraft world management plugin
permissions:
  hyperverse.worlds:
    description: Allows players to use the Hyperverse command
    default: op
  hyperverse.create:
    description: Allows players to create new worlds
    default: op
  hyperverse.list:
    description: Allows players to list worlds
    default: op
  hyperverse.teleport:
    description: Allows players to teleport between worlds
    default: op
